// Auto-generated calculator configurations
// Generated on: 2026-01-29T23:30:42.197Z
// Do not edit this file manually - it will be overwritten

export interface CalculatorConfig {
  id: string;
  name: string;
  description: string;
  csvFile: string;
  icon?: string;
  color?: string;
  labType?: string;
  format?: 'header-based' | 'section-based';
}

export const calculators: CalculatorConfig[] = [
  {
    "id": "colligative-properties",
    "name": "Colligative Properties Lab",
    "description": "Freezing point depression and molar mass determination",
    "csvFile": "/Colligative_Properties.csv",
    "icon": "🧊",
    "color": "#2196F3",
    "labType": "default",
    "format": "section-based"
  },
  {
    "id": "kakb-determination",
    "name": "Determination of $K_a$ and $K_b$",
    "description": "Dual-trial acid-base equilibrium calculations",
    "csvFile": "/KaKb_Determination.csv",
    "icon": "⚗️",
    "color": "#2196F3",
    "labType": "acid",
    "format": "section-based"
  },
  {
    "id": "molar-mass-volatile-liquid",
    "name": "Molar Mass of a Volatile Liquid",
    "description": "Calculate Molar Mass of a Volatile Liquid with 2 Trials",
    "csvFile": "/Molar_Mass_Volatile_Liquid.csv",
    "icon": "🌡️",
    "color": "#2196F3",
    "labType": "default",
    "format": "section-based"
  },
  {
    "id": "quant-prep-gas",
    "name": "Quantitative Preparation of a Gas",
    "description": "Calculation of the volume of gas produced",
    "csvFile": "/Quant_Prep_Gas.csv",
    "icon": "💨",
    "color": "#2196F3",
    "labType": "default",
    "format": "section-based"
  },
  {
    "id": "separation-of-a-mixture",
    "name": "Separation of a Mixture",
    "description": "Calculate mass percentages of components in a mixture",
    "csvFile": "/Separation of a Mixture.csv",
    "icon": "⚗️",
    "color": "#2196F3",
    "labType": "default",
    "format": "section-based"
  },
  {
    "id": "specific-heat-and-heat-transfer",
    "name": "Specific Heat and Heat Transfer",
    "description": "Laboratory calculation tool",
    "csvFile": "/Specific_Heat_and_Heat_Transfer.csv",
    "icon": "🔬",
    "color": "#2196F3",
    "labType": "default",
    "format": "section-based"
  },
  {
    "id": "titration-diprotic-acid",
    "name": "Titration of a Diprotic Acid",
    "description": "Single-trial titration calculations with equivalence points",
    "csvFile": "/Titration_Diprotic_Acid.csv",
    "icon": "🧪",
    "color": "#4CAF50",
    "labType": "titration",
    "format": "section-based"
  }
];

export const getCalculatorById = (id: string): CalculatorConfig | undefined => {
  return calculators.find(calc => calc.id === id);
};

export const getDefaultCalculator = (): CalculatorConfig => {
  return calculators[0] || {
    id: 'default',
    name: 'Lab Calculator',
    description: 'Laboratory calculation tool',
    csvFile: '/default.csv',
    icon: '🔬',
    color: '#2196F3'
  };
};

export const getCalculatorsByLabType = (labType: string): CalculatorConfig[] => {
  return calculators.filter(calc => calc.labType === labType);
};

export const getCalculatorsByFormat = (format: 'header-based' | 'section-based'): CalculatorConfig[] => {
  return calculators.filter(calc => calc.format === format);
};
