// Auto-generated calculator configurations
// Generated on: 2026-01-29T21:27:44.221Z
// Do not edit this file manually - it will be overwritten

export interface CalculatorConfig {
  id: string;
  name: string;
  description: string;
  csvFile: string;
  icon?: string;
  color?: string;
  labType?: string;
  format?: 'header-based' | 'section-based';
}

export const calculators: CalculatorConfig[] = [
  {
    "id": "colligative-properties-key-csv",
    "name": "Colligative Properties Lab",
    "description": "Laboratory calculation tool",
    "csvFile": "/Colligative Properties Key CSV_HeaderBased.csv",
    "icon": "🔬",
    "color": "#2196F3",
    "labType": "default",
    "format": "header-based"
  },
  {
    "id": "kakb",
    "name": "Determination of Ka and Kb",
    "description": "Dual-trial acid-base equilibrium calculations",
    "csvFile": "/KaKb_HeaderBased.csv",
    "icon": "⚗️",
    "color": "#2196F3",
    "labType": "acid",
    "format": "header-based"
  },
  {
    "id": "new-template-generic",
    "name": "Experiment Title",
    "description": "Generic lab template for testing section-based format",
    "csvFile": "/New_Template_Generic.csv",
    "icon": "🧪",
    "color": "#FF9800",
    "labType": "base",
    "format": "section-based"
  },
  {
    "id": "molar-mass-of-a-volatile-liquid",
    "name": "Molar Mass of a Volatile Liquid",
    "description": "Calculate Molar Mass of a Volatile Liquid with 2 Trials",
    "csvFile": "/Molar_mass_of_a_volatile_liquid_HeaderBased.csv",
    "icon": "🌡️",
    "color": "#4CAF50",
    "labType": "default",
    "format": "header-based"
  },
  {
    "id": "quant-prep-gas",
    "name": "Quantitative Preparation of a Gas",
    "description": "Calculation of the volume of gas",
    "csvFile": "/Quant_Prep_Gas_HeaderBased.csv",
    "icon": "🧪",
    "color": "#4CAF50",
    "labType": "default",
    "format": "header-based"
  },
  {
    "id": "titration",
    "name": "Titration of a Diprotic Acid",
    "description": "Single-trial titration calculations with equivalence points",
    "csvFile": "/Titration_HeaderBased.csv",
    "icon": "🧪",
    "color": "#4CAF50",
    "labType": "titration",
    "format": "header-based"
  }
];

export const getCalculatorById = (id: string): CalculatorConfig | undefined => {
  return calculators.find(calc => calc.id === id);
};

export const getDefaultCalculator = (): CalculatorConfig => {
  return calculators[0] || {
    id: 'default',
    name: 'Lab Calculator',
    description: 'Laboratory calculation tool',
    csvFile: '/default.csv',
    icon: '🔬',
    color: '#2196F3'
  };
};

export const getCalculatorsByLabType = (labType: string): CalculatorConfig[] => {
  return calculators.filter(calc => calc.labType === labType);
};

export const getCalculatorsByFormat = (format: 'header-based' | 'section-based'): CalculatorConfig[] => {
  return calculators.filter(calc => calc.format === format);
};
