import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { CalculationRow } from '../types';
import { renderWithKatex } from './katexRenderer';

export class PDFGenerator {
  private doc: jsPDF;
  private margin: number = 20;

  constructor() {
    this.doc = new jsPDF();
  }

  /**
   * Generate a PDF report with student data and results
   * Uses html2canvas to render KaTeX formatted content
   */
  async generateReport(rows: CalculationRow[], title: string, studentName?: string): Promise<void> {
    // Create a hidden container for rendering
    const container = document.createElement('div');
    container.id = 'pdf-render-container';
    container.style.cssText = `
      position: absolute;
      left: -9999px;
      top: 0;
      width: 800px;
      background: white;
      padding: 40px;
      font-family: 'Helvetica Neue', Arial, sans-serif;
    `;
    
    // Build the HTML content with KaTeX rendering
    container.innerHTML = this.buildReportHTML(rows, title, studentName);
    document.body.appendChild(container);

    try {
      // Wait for KaTeX fonts to load
      await new Promise(resolve => setTimeout(resolve, 100));
      
      // Capture the container with html2canvas
      const canvas = await html2canvas(container, {
        scale: 2, // Higher resolution
        useCORS: true,
        logging: false,
        backgroundColor: '#ffffff'
      });

      // Create PDF from canvas
      this.doc = new jsPDF('p', 'mm', 'a4');
      const imgData = canvas.toDataURL('image/png');
      
      // Calculate dimensions to fit on page
      const pdfWidth = this.doc.internal.pageSize.getWidth();
      const pdfHeight = this.doc.internal.pageSize.getHeight();
      const imgWidth = canvas.width;
      const imgHeight = canvas.height;
      
      // Scale to fit width with margins
      const availableWidth = pdfWidth - (this.margin * 2);
      const ratio = availableWidth / imgWidth;
      const scaledHeight = imgHeight * ratio;
      
      // Handle multi-page content
      let heightLeft = scaledHeight;
      let position = this.margin;
      let pageNum = 1;
      
      // First page
      this.doc.addImage(imgData, 'PNG', this.margin, position, availableWidth, scaledHeight);
      heightLeft -= (pdfHeight - this.margin * 2);
      
      // Add more pages if needed
      while (heightLeft > 0) {
        position = -(pdfHeight - this.margin * 2) * pageNum + this.margin;
        this.doc.addPage();
        this.doc.addImage(imgData, 'PNG', this.margin, position, availableWidth, scaledHeight);
        heightLeft -= (pdfHeight - this.margin * 2);
        pageNum++;
      }

      // Add page numbers
      const totalPages = this.doc.getNumberOfPages();
      for (let i = 1; i <= totalPages; i++) {
        this.doc.setPage(i);
        this.doc.setFontSize(8);
        this.doc.setTextColor(128);
        this.doc.text(`Page ${i} of ${totalPages}`, pdfWidth - 30, pdfHeight - 10);
        this.doc.text('Generated by Lab Calc', this.margin, pdfHeight - 10);
      }

      // Save the PDF
      const fileName = `${title.replace(/[^a-zA-Z0-9]/g, '_')}_Report.pdf`;
      this.doc.save(fileName);
    } finally {
      // Clean up
      document.body.removeChild(container);
    }
  }

  /**
   * Build HTML content for the report with KaTeX rendering
   */
  private buildReportHTML(rows: CalculationRow[], title: string, studentName?: string): string {
    const stats = this.calculateStats(rows);
    const groupedRows = this.groupRowsBySection(rows);
    
    let html = `
      <style>
        .pdf-report { font-size: 12px; line-height: 1.4; color: #333; }
        .pdf-title { font-size: 24px; font-weight: bold; margin-bottom: 10px; color: #1a365d; }
        .pdf-subtitle { font-size: 14px; color: #666; margin-bottom: 20px; }
        .pdf-section { margin-top: 20px; }
        .pdf-section-title { font-size: 16px; font-weight: bold; color: #2c5282; border-bottom: 2px solid #3182ce; padding-bottom: 5px; margin-bottom: 10px; }
        .pdf-subsection { margin: 15px 0; padding-left: 10px; border-left: 3px solid #63b3ed; }
        .pdf-subsection-title { font-size: 14px; font-weight: bold; color: #2b6cb0; margin-bottom: 8px; }
        .pdf-stats { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; margin: 20px 0; padding: 15px; background: #f7fafc; border-radius: 8px; }
        .pdf-stat { text-align: center; }
        .pdf-stat-value { font-size: 20px; font-weight: bold; color: #2c5282; }
        .pdf-stat-label { font-size: 10px; color: #666; }
        .pdf-row { display: flex; padding: 6px 0; border-bottom: 1px solid #e2e8f0; align-items: center; }
        .pdf-row-label { flex: 2; font-size: 11px; }
        .pdf-row-values { flex: 1; display: flex; gap: 15px; }
        .pdf-row-value { font-size: 11px; min-width: 80px; }
        .pdf-row-unit { flex: 0.5; font-size: 10px; color: #666; }
        .pdf-correct { color: #22543d; }
        .pdf-correct::before { content: '✓ '; color: #38a169; }
        .pdf-close { color: #744210; }
        .pdf-close::before { content: '~ '; color: #d69e2e; }
        .pdf-incorrect { color: #742a2a; }
        .pdf-incorrect::before { content: '✗ '; color: #e53e3e; }
        .pdf-pending { color: #666; font-style: italic; }
        .katex { font-size: 1em; }
      </style>
      <div class="pdf-report">
        <div class="pdf-title">${this.sanitizeAndRenderKatex(title)}</div>
        <div class="pdf-subtitle">
          ${studentName ? `Student: ${studentName} | ` : ''}
          Date: ${new Date().toLocaleDateString()}
        </div>
        
        <div class="pdf-stats">
          <div class="pdf-stat">
            <div class="pdf-stat-value">${stats.completionPercentage}%</div>
            <div class="pdf-stat-label">Completion</div>
          </div>
          <div class="pdf-stat">
            <div class="pdf-stat-value">${stats.accuracyPercentage}%</div>
            <div class="pdf-stat-label">Accuracy</div>
          </div>
          <div class="pdf-stat">
            <div class="pdf-stat-value">${stats.correctRows}/${stats.totalCheckable}</div>
            <div class="pdf-stat-label">Correct</div>
          </div>
        </div>
    `;

    // Add grouped rows
    Object.entries(groupedRows).forEach(([sectionTitle, subsections]) => {
      html += `
        <div class="pdf-section">
          <div class="pdf-section-title">${this.sanitizeAndRenderKatex(sectionTitle)}</div>
      `;
      
      Object.entries(subsections).forEach(([subsectionTitle, subsectionRows]) => {
        html += `
          <div class="pdf-subsection">
            <div class="pdf-subsection-title">${this.sanitizeAndRenderKatex(subsectionTitle)}</div>
        `;
        
        subsectionRows.forEach(row => {
          html += this.buildRowHTML(row);
        });
        
        html += '</div>';
      });
      
      html += '</div>';
    });

    html += '</div>';
    return html;
  }

  /**
   * Build HTML for a single row
   */
  private buildRowHTML(row: CalculationRow): string {
    const isSingleTrial = !row.trial2DataTag || row.trial2DataTag === '';
    
    let valuesHtml = '<div class="pdf-row-values">';
    
    if (row.trial1DataTag) {
      valuesHtml += this.buildValueHTML(
        row.studentValueTrial1, 
        row.studentChoiceTrial1,
        row.studentTextTrial1,
        row.isCorrectTrial1, 
        row.isCloseTrial1,
        row.entryType
      );
    }
    
    if (!isSingleTrial && row.trial2DataTag) {
      valuesHtml += this.buildValueHTML(
        row.studentValueTrial2, 
        row.studentChoiceTrial2,
        row.studentTextTrial2,
        row.isCorrectTrial2, 
        row.isCloseTrial2,
        row.entryType
      );
    }
    
    valuesHtml += '</div>';
    
    return `
      <div class="pdf-row">
        <div class="pdf-row-label">${this.sanitizeAndRenderKatex(row.label)}</div>
        ${valuesHtml}
        <div class="pdf-row-unit">${row.unit ? this.sanitizeAndRenderKatex(row.unit) : ''}</div>
      </div>
    `;
  }

  /**
   * Build HTML for a value cell with status indicator
   */
  private buildValueHTML(
    value: number | null, 
    choice: string | null | undefined,
    text: string | null | undefined,
    isCorrect: boolean | null, 
    isClose: boolean | null,
    entryType: string
  ): string {
    let displayValue: string;
    
    if (entryType === 'Choice' && choice !== null && choice !== undefined) {
      displayValue = choice;
    } else if (entryType === 'Text' && text !== null && text !== undefined) {
      displayValue = text;
    } else if (value !== null) {
      displayValue = this.formatNumber(value);
    } else {
      return '<div class="pdf-row-value pdf-pending">—</div>';
    }
    
    let className = 'pdf-row-value';
    if (isCorrect === true) {
      className += ' pdf-correct';
    } else if (isClose === true) {
      className += ' pdf-close';
    } else if (isCorrect === false) {
      className += ' pdf-incorrect';
    }
    
    return `<div class="${className}">${displayValue}</div>`;
  }

  /**
   * Format number for display
   */
  private formatNumber(value: number): string {
    if (Math.abs(value) < 0.001 || Math.abs(value) >= 10000) {
      return value.toExponential(3);
    }
    return value.toPrecision(4);
  }

  /**
   * Sanitize text and render KaTeX
   */
  private sanitizeAndRenderKatex(text: string): string {
    return renderWithKatex(text);
  }

  /**
   * Calculate summary statistics
   */
  private calculateStats(rows: CalculationRow[]): {
    totalRows: number;
    completedRows: number;
    correctRows: number;
    closeRows: number;
    incorrectRows: number;
    totalCheckable: number;
    completionPercentage: number;
    accuracyPercentage: number;
  } {
    // Filter to only calculation and calculated types for accuracy
    const checkableRows = rows.filter(row => 
      row.entryType === 'Calculation' || row.entryType === 'Calculated'
    );
    
    const completedRows = rows.filter(row => 
      row.studentValueTrial1 !== null || row.studentValueTrial2 !== null ||
      row.studentChoiceTrial1 !== null || row.studentChoiceTrial2 !== null ||
      row.studentTextTrial1 !== null || row.studentTextTrial2 !== null
    ).length;
    
    const correctRows = checkableRows.filter(row => 
      row.isCorrectTrial1 === true || row.isCorrectTrial2 === true
    ).length;
    
    const closeRows = rows.filter(row => 
      row.isCloseTrial1 === true || row.isCloseTrial2 === true
    ).length;
    
    const checkedRows = checkableRows.filter(row =>
      row.isCorrectTrial1 !== null || row.isCorrectTrial2 !== null
    ).length;
    
    const incorrectRows = rows.filter(row => 
      (row.isCorrectTrial1 === false && row.isCloseTrial1 !== true) || 
      (row.isCorrectTrial2 === false && row.isCloseTrial2 !== true)
    ).length;

    const completionPercentage = rows.length > 0 ? Math.round((completedRows / rows.length) * 100) : 0;
    const accuracyPercentage = checkedRows > 0 ? Math.round((correctRows / checkedRows) * 100) : 0;

    return {
      totalRows: rows.length,
      completedRows,
      correctRows,
      closeRows,
      incorrectRows,
      totalCheckable: checkableRows.length,
      completionPercentage,
      accuracyPercentage
    };
  }

  /**
   * Group rows by section and subsection
   */
  private groupRowsBySection(rows: CalculationRow[]): { [key: string]: { [key: string]: CalculationRow[] } } {
    return rows.reduce((acc, row) => {
      const sectionTitle = row.section;
      const subsectionTitle = row.subsection;

      if (!acc[sectionTitle]) {
        acc[sectionTitle] = {};
      }
      
      if (!acc[sectionTitle][subsectionTitle]) {
        acc[sectionTitle][subsectionTitle] = [];
      }
      acc[sectionTitle][subsectionTitle].push(row);
      return acc;
    }, {} as { [key: string]: { [key: string]: CalculationRow[] } });
  }
}
